cache:
  directories:
    - node_modules
    - .nvm

install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 5


script:
  - npm test
  - npm run lint

notifications:
  slack: veckopengen:uRAtf0cYPUxlDqTDPBzSEa8R